"""Explicit object/task rules. They nominate labels; semantic support is also required.

One canonical owner per rule prevents copying the same candidate under many parents.
Multiple equally explicit tasks are retained for review, never merged by transitivity.
Regex is deliberately limited to unambiguous Chinese/English technical expressions;
other languages can retain a parent or enter recovery review rather than be guessed.
"""
RULES=[]
def R(parent,key,name,obj,task='',exclude='',child=True,scope=''):
    RULES.append(dict(rule_id=f'{parent}.{key}',parent_id=parent,topic_id=f'{parent}.{key}' if child else parent,
        name=name,object_pattern=obj,task_pattern=task,exclude_title_pattern=exclude,
        is_child=child,definition=scope or f'研究对象须匹配“{name}”对应对象，且满足所列任务；多任务冲突保留复核。',
        review_basis='对象/任务定义及既有486目录、1000候选、已完成重合审计；逐条规则命中另需向量支持'))

B=r'\bbatter(?:y|ies)\b|电池|电芯'
LIB=r'lithium.ion|li.ion|锂离子'
LM=r'lithium.metal|li.metal|锂金属|金属锂'
NA=r'sodium.ion|sodium.metal|na.ion|钠离子|钠电池'
PV=r'photovoltaic|solar.cell|solar.module|光伏|太阳能电池'
PC=r'photo(?:electro)?catal|photo.catal|光(?:电)?催化|photodegrad|光降解'
PE=r'perovskite.{0,35}(solar|cell)|钙钛矿.{0,15}(太阳能|光伏|电池)'
FC=r'fuel.cell|燃料电池'
WIND=r'wind.turbine|wind.farm|wind.power|wind.energy|风电|风力机|风力发电'
GRID=r'power.system|power.grid|electric.{0,12}grid|电网|电力系统|配电'

# Electrochemical storage: combine overlapping materials/interfaces when needed.
R('M000','cooling','电池冷却与散热',B,r'cooling|heat.dissipation|thermal.management|冷却|散热|热管理',r'fuel.cell|燃料电池|solar.cell|太阳能电池|退火|TOPCon')
R('M000','preheating','电池低温预热',B,r'preheat|low.temperature.heating|self.heating|预热|低温加热',r'fuel.cell|燃料电池')
R('M027','charger_thermal','充电设施散热',r'charging.station|charging.pile|充电桩|充电站',r'cooling|thermal.management|heat.dissipation|散热|冷却|热管理')
R('M348','runaway','电池热失控与传播',B,r'thermal.runaway|thermal.propagation|热失控|热蔓延')
R('M348','fire','电池火灾抑制与灭火',B,r'fire.suppress|fire.extinguish|fire.safety|灭火|火灾抑制|阻燃')
R('M169','soc','电池荷电状态估计',B,r'state.of.charge|\bSOC\b|荷电状态',r'state.of.health|\bSOH\b|remaining.useful.life|健康状态|剩余寿命')
R('M169','soh_rul','电池健康状态与寿命预测',B,r'state.of.health|\bSOH\b|remaining.useful.life|battery.lifetime|健康状态|剩余寿命|寿命预测')
R('M169','ecm','电池等效电路与参数辨识',B,r'equivalent.circuit|parameter.identification|parameter.estimation|等效电路|参数辨识',r'state.of.charge|state.of.health|荷电状态|健康状态')
R('M296','second_life','动力电池梯次利用',B,r'second.life|repurpos|梯次利用|梯次使用')
R('M297','balancing','电池单体均衡控制',B,r'cell.balanc|charge.balanc|equaliz|均衡')
R('M206','impedance','电池阻抗表征',B,r'impedance.spectroscop|electrochemical.impedance|阻抗谱|阻抗表征')
R('M206','aging','电池老化实验与循环寿命',B,r'aging|ageing|cycle.life|calendar.life|老化|循环寿命',r'prediction|forecast|estimat|预测|估计')
R('M049','solid','固态聚合物锂电解质',r'polymer.electrolyte|聚合物电解质|聚合物固态电解质',r'solid|固态|固体',r'gel.polymer|凝胶|proton|质子|sodium|钠|zinc|锌')
R('M049','gel','凝胶聚合物锂电解质',r'polymer.electrolyte|聚合物电解质|聚合物凝胶电解质',r'gel|凝胶',r'proton|质子|sodium|钠|zinc|锌|supercapacitor|超级电容')
R('M048','separator','电池隔膜制备与改性',B,r'separator|separating.membrane|隔膜',r'fuel.cell|燃料电池|membrane.reactor')
R('M048','binder','电池电极粘结剂',B,r'\bbinder|binding.agent|粘结剂|黏结剂')
R('M453','electrolyte','液态电池电解液与添加剂',B,r'electrolyte.additive|electrolyte.formulat|solvation.structure|电解液添加剂|电解液配方|溶剂化结构',r'lithium.metal|li.metal|锂金属|solid.polymer|固态聚合物',False)
R('M223','interface','锂金属负极界面稳定与枝晶抑制',LM,r'dendrit|interphase|interface|anode.protect|artificial.SEI|枝晶|界面|负极保护|\bSEI\b')
R('M447','anode','钠离子电池负极材料',NA,r'anod|负极',r'cathod.{0,20}anod|正负极')
R('M447','cathode','钠离子电池正极材料',NA,r'cathod|positive.electrode|正极',r'cathod.{0,20}anod|正负极')
R('M021','electrolyte','钠电池电解液与界面',NA,r'electrolyte|interphase|电解液|电解质|界面')
R('M108','zinc_ion','水系锌离子电池',r'zinc.ion.batter|aqueous.zinc.batter|锌离子电池|水系锌电池')
R('M108','zinc_air','锌空气电池',r'zinc.air.batter|锌空气电池|锌空电池')
R('M414','zinc_anode','水系锌电池负极界面稳定',r'zinc|\bZn\b|锌',r'anode.{0,35}(dendrit|interface|stabil)|dendrit.{0,30}anode|锌负极|负极界面|抑制锌枝晶','',False)
R('M261','lithium_sulfur','锂硫电池与多硫化物调控',r'lithium.sulfur.batter|li.s.batter|锂硫电池|polysulfide.shuttl|多硫化物穿梭','','',False)
R('M421','lfp','锂电磷酸盐正极材料',r'lithium.iron.phosphate|LiFePO4|LiMnPO4|磷酸铁锂|磷酸锰铁锂',r'cathod|positive.electrode|正极|batter|电池')
R('M421','layered','层状及富镍锂电正极材料',r'nickel.rich|Ni.rich|layered.oxide|NCM|NMC|富镍|高镍|层状氧化物',r'cathod|positive.electrode|正极',r'sodium|钠')
R('M341','silicon','锂电硅基负极',r'silicon|硅|Si/C|SiOx',r'anode|负极',r'solar|光伏|cathode|正极',False)
R('M279','graphite','锂电石墨负极',r'graphite|石墨',r'anode|负极',r'sodium|钠|graphene|石墨烯')
R('M374','multivalent','镁铝钙多价离子电池',r'magnesium.ion.batter|aluminum.ion.batter|aluminium.ion.batter|calcium.ion.batter|镁离子电池|铝离子电池|钙离子电池')
R('M374','potassium','钾离子电池',r'potassium.ion.batter|钾离子电池')
R('M327','sulfide_electrolyte','硫化物固态电解质',r'sulfide|sulphide|硫化物|argyrodite|硫银锗矿',r'solid.electrolyte|solid.state.electrolyte|固态电解质|固体电解质',r'lithium.sulfur|锂硫')
R('M301','hydrometallurgy','废旧电池湿法回收',r'spent.batter|battery.recycl|废旧.{0,8}电池|电池回收',r'leach|hydrometall|浸出|湿法')
R('M301','direct_recycling','废旧电池材料直接再生',r'spent.batter|battery.recycl|废旧.{0,8}电池|电池回收',r'direct.recycl|direct.regener|relithiat|直接再生|补锂|直接回收')
R('M301','disassembly','废旧电池拆解与物理分离',r'spent.batter|battery.recycl|废旧.{0,8}电池|电池回收',r'disassembl|dismantl|physical.separat|拆解|破碎|物理分离')
R('M055','sizing','储能容量配置与选址',r'energy.storage|储能',r'sizing|capacity.allocation|optimal.placement|容量配置|容量优化|选址',r'batter.{0,15}material|电极材料')
R('M055','dispatch','储能运行调度与收益',r'energy.storage|储能',r'dispatch|scheduling|arbitrage|运行调度|套利',r'microgrid|微电网|integrated.energy|综合能源')
R('M483','integration','储能系统集成与安全装置',r'energy.storage.system|energy.storage.cabinet|储能系统|储能柜',r'integrat|fire.protect|safety|集成|消防|安全')

# Solar technology; known overlapping TiO2/ZnO/HER clusters feed common owners.
R('M066','tandem','钙钛矿叠层太阳能电池',PE,r'tandem|multijunction|multi.junction|叠层|多结')
R('M066','interfaces','钙钛矿电池界面、钝化与传输层',PE,r'passivat|interface|transport.layer|transport.material|钝化|界面|传输层|传输材料',r'tandem|叠层|multi.junction|多结')
R('M066','crystallization','钙钛矿吸收层结晶与成膜',PE,r'crystalliz|crystallis|grain.growth|film.formation|结晶|晶粒|成膜',r'tandem|叠层|transport.layer|传输层')
R('M066','stability','钙钛矿电池稳定性与衰减',PE,r'degradation|moisture.stability|thermal.stability|operational.stability|衰减|湿度稳定|热稳定|运行稳定',r'tandem|叠层|passivat|钝化|interface|界面')
R('M158','polymer','聚合物有机太阳能电池',r'polymer.solar.cell|polymer.photovoltaic|聚合物太阳能电池|聚合物光伏')
R('M158','small_molecule','小分子有机太阳能电池',r'organic.solar.cell|organic.photovoltaic|有机太阳能|有机光伏',r'small.molecul|小分子',r'polymer.solar|聚合物太阳能')
R('M158','printing','有机光伏印刷与规模制造',r'organic.solar.cell|organic.photovoltaic|有机太阳能|有机光伏',r'roll.to.roll|gravure|slot.die|printing|卷对卷|印刷|狭缝涂布')
R('M360','photoanode','染料敏化电池光阳极',r'dye.sensiti[sz]ed|\bDSSC|染料敏化',r'photoanode|photoelectrode|光阳极|光电极',r'counter.electrode|对电极')
R('M360','counterelectrode','染料敏化电池对电极',r'dye.sensiti[sz]ed|\bDSSC|染料敏化',r'counter.electrode|对电极')
R('M360','sensitizer','染料敏化电池敏化剂',r'dye.sensiti[sz]ed|\bDSSC|染料敏化',r'sensitizer|sensitiser|organic.dye|natural.dye|extracted.dye|co.sensiti|敏化剂|有机染料|天然染料|共敏化',r'counter.electrode|对电极')
R('M085','fault','光伏组件故障与缺陷检测',PV,r'fault|defect|diagnos|故障|缺陷|诊断')
R('M085','degradation','光伏组件退化与寿命',PV,r'degradation|aging|ageing|lifetime|退化|老化|寿命',r'perovskite|钙钛矿')
R('M137','parameters','光伏组件模型参数辨识',PV,r'parameter.identification|parameter.estimation|parameter.extraction|参数辨识|参数估计|参数提取')
R('M387','power_forecast','光伏发电功率预测',PV,r'power.forecast|power.prediction|generation.forecast|generation.prediction|功率预测|发电量预测','',False)
R('M159','irradiance','太阳辐照度预测估算',r'solar.irradian|solar.radiation|太阳辐射|太阳辐照',r'forecast|predict|estimat|预测|估算|估计')
R('M376','measurement','太阳辐射测量与仪器',r'solar.irradian|solar.radiation|太阳辐射|太阳辐照',r'measurement|pyranometer|radiometer|测量|辐射表|辐射计')
R('M239','rooftop','屋顶与分布式光伏部署',PV,r'rooftop|distributed|屋顶|分布式')
R('M239','economics','光伏技术经济与投资',PV,r'techno.economic|levelized.cost|investment|payback|技术经济|平准化|投资回收',r'rooftop|distributed|屋顶|分布式')
R('M239','agrivoltaics','农光互补与农光协同',r'agrivoltaic|agro.photovoltaic|农光互补|农光协同')
R('M435','pvt','光伏光热联合系统',r'photovoltaic.thermal|photovoltaic/thermal|光伏光热|PV/T')
R('M333','collector','太阳能集热器传热设计',r'solar.collector|太阳能集热器',r'heat.transfer|thermal.performance|design|传热|热性能|设计')
R('M333','csp','聚光太阳能热发电',r'concentrated.solar.power|concentrating.solar.power|solar.tower|solar.thermal.power|聚光太阳能|塔式光热|太阳能热发电')
R('M034','water_heating','太阳能热水与供热装置',r'solar|太阳能',r'water.heat|space.heat|热水|供热|采暖',r'photovoltaic|光伏')
R('M130','manufacturing','光伏电池与组件制造工艺',PV,r'manufactur|fabrication|laminat|encapsulat|制造|层压|封装',r'organic|polymer|perovskite|dye.sensiti|有机|聚合物|钙钛矿|染料敏化')
R('M166','multijunction','非钙钛矿多结太阳能电池',r'solar.cell|太阳能电池',r'multi.junction|multijunction|tandem|多结|叠层',r'perovskite|钙钛矿')

# Hydrogen, catalytic reactions and environmental applications.
R('M010','photocatalytic_h2','光催化制氢',PC,r'hydrogen.evolution|hydrogen.production|hydrogen.generation|\bH2.production|析氢|制氢',r'carbon.dioxide.reduc|CO2.reduc|二氧化碳还原')
R('M010','biophotolysis','光生物制氢',r'photoferment|biophotolysis|photobiological|光发酵|光生物',r'hydrogen|氢')
R('M036','co2_photo','光催化二氧化碳还原',PC,r'CO2|carbon.dioxide|二氧化碳')
R('M112','pollutants','TiO₂光催化污染物降解',r'TiO\s*2|titanium.dioxide|二氧化钛',r'photodegrad|photocatalytic.degrad|photocatalytic.oxid|光催化降解|光降解|pollutant|dye.degrad|污染物|染料降解')
R('M203','pollutants','ZnO光催化污染物降解',r'\bZnO\b|zinc.oxide|氧化锌',r'photodegrad|photocatalytic.degrad|光催化降解|光降解|dye.degrad|染料降解')
R('M079','other_pollutants','其他材料光催化污染物降解',PC,r'degrad|pollutant|污染物|降解',r'TiO\s*2|titanium.dioxide|二氧化钛|\bZnO\b|zinc.oxide|氧化锌')
R('M235','pec_water','光电化学水分解',r'photoelectrochemical|光电化学',r'water.splitting|hydrogen|水分解|制氢','',False)
R('M256','her','电催化析氢',r'electrocatal|electrochemical|电催化|电化学',r'hydrogen.evolution|析氢|\bHER\b',r'overall.water.splitting|整体水分解|photocatal|光催化',False)
R('M154','oer','电催化析氧',r'electrocatal|electrochemical|电催化|电化学',r'oxygen.evolution|析氧|\bOER\b',r'overall.water.splitting|整体水分解|oxygen.reduction|氧还原',False)
R('M363','orr','氧还原电催化',r'electrocatal|electrochemical|电催化|电化学',r'oxygen.reduction|氧还原|\bORR\b',r'oxygen.evolution|析氧',False)
R('M281','overall_water','整体电催化水分解',r'electrocatal|electroly|电催化|电解',r'overall.water.splitting|overall.water.electrolysis|整体水分解|全解水','',False)
R('M008','co2_electro','二氧化碳电还原',r'electroreduc|electrocatal|electrochemical|电还原|电催化|电化学',r'CO2|carbon.dioxide|二氧化碳','',False)
R('M255','co2_hydrogenation','二氧化碳加氢制燃料',r'CO2|carbon.dioxide|二氧化碳',r'hydrogenation|methanation|加氢|甲烷化')
R('M474','n2_reduction','氮气电还原制氨',r'nitrogen.reduction|N2.reduction|氮气还原',r'electrocatal|electrochemical|电催化|电化学')
R('M474','nitrate_reduction','硝酸盐电还原制氨',r'nitrate.reduction|硝酸盐还原',r'ammonia|氨')
R('M136','alkaline_electrolysis','碱性水电解制氢',r'water.electroly|electrolyzer|electrolyser|水电解|电解槽',r'alkaline|碱性')
R('M136','pem_electrolysis','质子交换膜水电解制氢',r'water.electroly|electrolyzer|electrolyser|水电解|电解槽',r'proton.exchange.membrane|\bPEM\b|质子交换膜')
R('M124','steam_reforming','蒸汽重整制氢与合成气',r'steam.reform|蒸汽重整|水蒸气重整',r'hydrogen|syngas|制氢|合成气')
R('M124','dry_reforming','二氧化碳干重整制合成气',r'dry.reform|干重整|二氧化碳重整')
R('M071','economics','氢能技术经济与生命周期',r'hydrogen|氢能|制氢',r'techno.economic|life.cycle|levelized.cost|技术经济|生命周期|平准化')
R('M238','supply_chain','氢能供应链与基础设施规划',r'hydrogen|氢能',r'supply.chain|infrastructure|network.planning|供应链|基础设施|网络规划')
R('M086','refueling','加氢站与氢气加注',r'hydrogen.refuel|hydrogen.filling|加氢站|氢气加注')
R('M192','solid_storage','固态储氢材料',r'hydrogen.storage|储氢',r'hydride|solid.state|metal.alloy|氢化物|固态|合金','',False)
R('M482','pemfc','质子交换膜燃料电池系统',r'proton.exchange.membrane.fuel.cell|polymer.electrolyte.fuel.cell|\bPEMFC\b|质子交换膜燃料电池')
R('M259','sofc','固体氧化物燃料电池',r'solid.oxide.fuel.cell|\bSOFC\b|固体氧化物燃料电池','','',False)
R('M426','soec','固体氧化物电解池',r'solid.oxide.electrolysis|solid.oxide.electrolyzer|\bSOEC\b|固体氧化物电解池','','',False)
R('M078','water','燃料电池水管理',FC,r'water.management|flooding|water.transport|水管理|水淹|水传输')
R('M078','air','燃料电池供气与空压控制',FC,r'air.supply|air.compressor|oxygen.excess|供气|空压机|氧过量')
R('M268','proton_membrane','燃料电池质子交换膜材料',r'proton.exchange.membrane|proton.conducting.membrane|质子交换膜|质子传导膜',r'fuel.cell|燃料电池',r'electrolyzer|electrolyser|电解槽',False)
R('M228','persulfate','过硫酸盐活化高级氧化',r'persulfate|peroxymonosulfate|peroxydisulfate|过硫酸盐|过一硫酸盐',r'activat|oxidation|活化|氧化','',False)
R('M324','absorption','二氧化碳溶剂吸收捕集',r'CO2|carbon.dioxide|二氧化碳',r'amine|solvent.absorp|chemical.absorp|胺|溶剂吸收|化学吸收')
R('M324','adsorption','二氧化碳固体吸附捕集',r'CO2|carbon.dioxide|二氧化碳',r'adsorp|sorbent|吸附',r'carbon.aerogel|activated.carbon|活性炭|碳气凝胶')
R('M150','carbon_capture','多孔碳二氧化碳吸附',r'carbon|炭|碳',r'CO2.adsorp|CO2.capture|carbon.dioxide.adsorp|carbon.dioxide.capture|二氧化碳吸附|二氧化碳捕集','',False)
R('M196','dac','直接空气捕碳',r'direct.air.capture|直接空气捕|空气直接捕')
R('M486','geological','二氧化碳地质封存',r'CO2|carbon.dioxide|二氧化碳',r'geological.storage|geologic.storage|geological.sequestration|地质封存|地质储存','',False)
R('M114','hydrate','二氧化碳水合物分离与储存',r'CO2|carbon.dioxide|二氧化碳',r'hydrate|水合物')
R('M046','fouling','分离膜污染与清洗',r'membrane|膜',r'fouling|antifouling|cleaning|膜污染|抗污染|膜清洗')
R('M046','desalination','膜法海水淡化',r'membrane|reverse.osmosis|膜|反渗透',r'desalin|海水淡化')
R('M468','adsorption','水污染物吸附去除',r'wastewater|water.pollut|aqueous.solution|废水|水污染|水溶液',r'adsorp|吸附',r'photocatal|光催化')
R('M468','electro_oxidation','水污染物电化学氧化',r'wastewater|water.pollut|废水|水污染',r'electrochemical.oxid|electro.oxid|电化学氧化|电氧化')

# Biomass: conversion route, not interchangeable references to biogas.
R('M128','food_sludge','有机废物与污泥厌氧消化',r'anaerobic.digestion|anaerobic.co.digestion|厌氧消化|厌氧共消化',r'food.waste|sludge|餐厨|厨余|污泥')
R('M128','manure','畜禽粪便与农业残余厌氧消化',r'anaerobic.digestion|anaerobic.co.digestion|厌氧消化|厌氧共消化',r'manure|dung|agricultural.residue|粪便|粪污|秸秆',r'food.waste|sludge|餐厨|厨余|污泥')
R('M274','biogas_upgrading','沼气提纯与生物甲烷升级',r'biogas|biomethane|沼气|生物甲烷',r'upgrad|purif|CO2.removal|提纯|净化|脱碳')
R('M274','biogas_process','厌氧产沼气工艺与建模',r'biogas.production|methane.yield|biomethane.production|沼气生产|沼气产量|产甲烷',r'digest|ferment|model|消化|发酵|建模',r'gasification|热解|气化')
R('M058','fermentative_h2','厌氧发酵生物制氢',r'dark.ferment|anaerobic.ferment|暗发酵|厌氧发酵',r'hydrogen|氢')
R('M087','anaerobic_wastewater','厌氧污水处理反应器',r'anaerobic|厌氧|\bUASB\b|\bAnMBR\b',r'wastewater.treatment|污水处理|废水处理')
R('M033','sludge_dewatering','污泥脱水与调理',r'sludge|污泥',r'dewater|condition|脱水|调理')
R('M033','nutrient_recovery','污水污泥营养元素回收',r'sludge|wastewater|污泥|废水|污水',r'phosphorus.recover|nitrogen.recover|struvite|磷回收|氮回收|鸟粪石')
R('M347','gasification','生物质气化制合成气',r'biomass|wood|生物质|木质',r'gasification|gasifier|气化')
R('M347','htl','生物质水热液化',r'biomass|alga|生物质|藻',r'hydrothermal.liquefaction|水热液化')
R('M347','htc','生物质水热炭化',r'biomass|生物质|sludge|污泥',r'hydrothermal.carbonization|hydrothermal.carbonisation|水热炭化|水热碳化')
R('M062','pyrolysis','生物质热解与炭化',r'biomass|wood|生物质|木质',r'pyroly|carbonization|carbonisation|热解|炭化',r'coal|煤',False)
R('M226','soil','生物炭土壤改良',r'biochar|生物炭',r'soil|土壤')
R('M226','water','生物炭水污染物去除',r'biochar|生物炭',r'wastewater|aqueous|pollutant|废水|水污染|污染物',r'soil|土壤')
R('M365','activated_carbon','活性炭制备与孔结构',r'activated.carbon|活性炭',r'synthesis|prepar|activation|pore.structure|制备|活化|孔结构',r'supercapacitor|battery|超级电容|电池|CO2.capture|二氧化碳捕集')
R('M224','pretreatment','木质纤维素预处理',r'lignocellulos|cellulosic.biomass|木质纤维素',r'pretreat|delignif|预处理|脱木质素')
R('M224','ethanol','木质纤维素生物乙醇',r'lignocellulos|cellulosic.biomass|木质纤维素',r'ethanol|乙醇')
R('M015','algal_biofuel','藻类生物燃料',r'alga|藻',r'biofuel|biodiesel|生物燃料|生物柴油')
R('M015','sustainability','生物能源生命周期与可持续性',r'bioenergy|biomass|biofuel|生物能源|生物质|生物燃料',r'life.cycle|sustainab|生命周期|可持续')
R('M439','ewaste','电子废物回收',r'electronic.waste|e.waste|电子废物|电子垃圾',r'recycl|recover|回收')
R('M439','plastic','废塑料回收与转化',r'waste.plastic|plastic.waste|废塑料',r'recycl|pyroly|conversion|回收|热解|转化')

# Power systems, forecasting and charging: do not conflate measured quantities.
R('M400','load','电力负荷预测',r'electric.{0,8}load|power.load|electricity.demand|电力负荷|用电负荷|电力需求',r'forecast|predict|预测',r'electricity.price|电价')
R('M400','price','电价预测',r'electricity.price|power.price|电价',r'forecast|predict|预测')
R('M175','short_circuit','电网短路电流计算',GRID,r'short.circuit.current|fault.current.calcul|短路电流|短路计算')
R('M332','wind_speed','风速预测',r'wind.speed|风速',r'forecast|predict|预测')
R('M332','wind_power','风电出力预测',WIND,r'power.forecast|power.prediction|generation.forecast|功率预测|出力预测|发电量预测',r'wind.speed.forecast|风速预测')
R('M444','wind_condition','风机状态监测与预测性维护',WIND,r'condition.monitor|predictive.maintenance|fault.diagnos|状态监测|预测性维护|故障诊断')
R('M253','location','电动汽车充电站选址规划',r'electric.vehicle|EV.charg|charging.station|电动汽车|充电站',r'location|siting|placement|选址|站点规划',r'routing|路径')
R('M253','routing','电动汽车路径与补能规划',r'electric.vehicle|电动汽车|electric.bus|电动公交',r'routing|route.planning|路径|行驶路线')
R('M089','scheduling','电动汽车有序充放电调度',r'electric.vehicle|EV.charg|电动汽车|电动公交',r'charging.schedul|charging.strateg|smart.charging|coordinated.charging|orderly.charging|充电调度|有序充电|充电策略|充放电调度')
R('M027','grid_impact','电动汽车充电并网影响',r'electric.vehicle|电动汽车|charging.station|充电站',r'grid.impact|grid.integration|distribution.network|并网影响|电网影响|配电网')
R('M191','charging_forecast','电动汽车充电负荷预测',r'charging.load|charging.demand|充电负荷|充电需求',r'forecast|predict|预测')
R('M105','adoption','电动汽车推广与购买行为',r'electric.vehicle|电动汽车',r'adoption|purchase|consumer|acceptance|推广|购买|消费者|接受度')
R('M105','consumption','电动汽车整车能耗与续航',r'electric.vehicle|电动汽车',r'energy.consumption|driving.range|能耗|续航')
R('M104','ems','微电网能量管理与经济调度',r'microgrid|micro.grid|微电网',r'energy.management|economic.dispatch|optimal.schedul|能量管理|经济调度|优化调度')
R('M142','droop','微电网下垂控制与功率分配',r'microgrid|micro.grid|微电网',r'droop.control|power.sharing|下垂控制|功率分配')
R('M142','islanding','微电网孤岛切换与动态控制',r'microgrid|micro.grid|微电网',r'islanding|islanded|transition|secondary.control|孤岛|并离网切换|二次控制',r'droop.control|下垂控制')
R('M260','scheduling','综合能源系统优化调度',r'integrated.energy.system|multi.energy.system|energy.hub|综合能源系统|多能源系统|能源枢纽',r'dispatch|schedul|调度')
R('M260','planning','综合能源系统规划配置',r'integrated.energy.system|multi.energy.system|energy.hub|综合能源系统|多能源系统|能源枢纽',r'planning|sizing|capacity.allocation|规划|容量配置',r'dispatch|schedul|调度')
R('M248','vpp','虚拟电厂资源聚合与调度',r'virtual.power.plant|虚拟电厂','','',False)
R('M047','demand_response','配电网需求响应与柔性调度',r'distribution.network|distribution.system|配电网',r'demand.response|flexib|需求响应|柔性')
R('M431','planning','配电网规划与容量配置',r'distribution.network|distribution.system|配电网',r'planning|capacity.allocation|规划|容量配置')
R('M415','reconfiguration','配电网重构',r'distribution.network|distribution.system|配电网',r'reconfigur|重构','',False)
R('M082','voltage_var','配电网电压无功优化',r'distribution.network|distribution.system|配电网',r'volt.var|reactive.power|voltage.regulation|电压无功|无功优化|电压调节')
R('M082','harmonics','配电网谐波与电能质量治理',r'distribution.network|distribution.system|配电网',r'harmonic|power.quality|谐波|电能质量')
R('M470','state_estimation','电网状态估计与相量测量',GRID,r'state.estimation|phasor.measurement|状态估计|相量测量')
R('M463','transient','电力系统暂态稳定',GRID,r'transient.stability|暂态稳定')
R('M463','voltage','电力系统电压稳定',GRID,r'voltage.stability|voltage.collapse|电压稳定|电压崩溃')
R('M317','frequency','电网频率控制',GRID,r'frequency.control|frequency.regulation|load.frequency|频率控制|调频|负荷频率')
R('M221','reliability','电力系统可靠性评估',GRID,r'reliability.assessment|reliability.evaluation|可靠性评估|可靠性评价')
R('M101','transformer','变压器故障诊断',r'transformer|变压器',r'fault|diagnos|故障|诊断',r'power.electronic.transformer|电力电子变压器')
R('M101','line_fault','输配电线路故障定位',r'transmission.line|distribution.line|power.line|输电线路|配电线路|电力线路',r'fault.locat|fault.detect|故障定位|故障检测')
R('M101','switchgear','开关设备故障检测',r'switchgear|circuit.breaker|开关柜|断路器',r'fault|diagnos|condition.monitor|故障|诊断|状态监测')
R('M164','lightning','输电线路雷击与防雷',r'transmission.line|power.line|输电线路|电力线路',r'lightning|雷击|防雷')
R('M164','grounding','电网接地与地网安全',r'grounding.grid|earthing.grid|grounding.system|接地网|接地系统',r'design|resistance|safety|设计|电阻|安全')
R('M222','partial_discharge','电气绝缘局部放电',r'partial.discharge|局部放电',r'insulat|cable|transformer|绝缘|电缆|变压器')
R('M222','corona','电晕放电与电晕损耗',r'corona.discharge|corona.loss|电晕放电|电晕损耗')
R('M353','cyber','智能电网网络攻击与安全',r'smart.grid|power.grid|电网',r'cyber.attack|cyber.security|false.data.injection|网络攻击|网络安全|虚假数据注入')
R('M353','resilience','电网灾害韧性与恢复',GRID,r'resilien|disaster|restoration|韧性|灾害|恢复供电')
R('M081','communication','智能电网通信架构',r'smart.grid|智能电网',r'communication|network.architecture|通信|网络架构',r'cyber|网络安全')
R('M119','plc','电力线载波通信',r'power.line.communication|power.line.carrier|电力线载波|电力载波')
R('M446','metering','智能电表与用能监测',r'smart.meter|energy.monitor|智能电表|用能监测',r'electric|energy|电|能')
R('M123','carbon_dispatch','电力系统碳排放计量与调度',GRID,r'carbon.emission|carbon.flow|low.carbon.dispatch|碳排放|碳流|低碳调度')
R('M135','market_design','电力市场机制与制度设计',r'electricity.market|power.market|电力市场',r'market.design|mechanism|market.reform|机制|制度|改革')
R('M135','prosumer','产消者能源交易',r'prosumer|产消者|peer.to.peer.energy|点对点能源交易')
R('M155','bidding','电力交易竞价与报价',r'electricity.market|power.market|电力市场|electricity.trad|电力交易',r'bidding|offer.strateg|竞价|报价','',False)

# Electrical machines, electronics and identifiable mechanical objects.
R('M212','isolated','隔离型DC-DC变换器',r'DC.DC|直流.直流|直流变换器',r'\bisolated\b|隔离',r'non.isolated|非隔离')
R('M212','nonisolated','非隔离DC-DC变换器',r'DC.DC|直流.直流|直流变换器',r'non.isolated|非隔离')
R('M236','resonant','谐振与软开关变换器',r'converter|变换器|转换器',r'resonant|soft.switch|zero.voltage.switch|谐振|软开关|零电压开关')
R('M478','pfc','功率因数校正电路与控制',r'power.factor.correction|功率因数校正|\bPFC\b')
R('M485','multilevel','多电平逆变器',r'multilevel.inverter|multi.level.inverter|多电平逆变器','','',False)
R('M315','power_semiconductor','功率半导体器件',r'power.MOSFET|\bIGBT\b|power.semiconductor|功率半导体|功率MOSFET',r'device|switch|器件|开关')
R('M012','packaging','集成电路与功率模块封装',r'integrated.circuit|chip|power.module|集成电路|芯片|功率模块',r'packaging|encapsulat|封装')
R('M302','fet','场效应晶体管结构与建模',r'field.effect.transistor|场效应晶体管|MOSFET',r'model|structure|建模|结构',r'power.MOSFET|功率MOSFET')
R('M337','fpga','FPGA实时控制与硬件实现',r'\bFPGA\b|现场可编程',r'control|implement|real.time|控制|实现|实时')
R('M096','magnet_design','永磁电机磁路与结构设计',r'permanent.magnet.motor|永磁电机|永磁同步电机',r'design|magnetic.circuit|rotor|设计|磁路|转子')
R('M380','pmsm_control','永磁同步电机控制',r'permanent.magnet.synchronous|\bPMSM\b|永磁同步',r'control|drive|控制|驱动')
R('M392','induction_control','感应与异步电机驱动控制',r'induction.motor|asynchronous.motor|感应电机|异步电机',r'control|drive|控制|驱动','',False)
R('M276','torque','电机转矩脉动抑制',r'motor|电机',r'torque.ripple|cogging.torque|转矩脉动|齿槽转矩')
R('M276','modulation','电机驱动PWM与谐波控制',r'motor|电机',r'PWM|pulse.width.modulation|harmonic|脉宽调制|谐波')
R('M141','rotor','电机转子结构与制造',r'motor|电机',r'rotor|转子',r'stator|定子')
R('M141','stator','电机定子结构与制造',r'motor|电机',r'stator|定子',r'rotor|转子')
R('M492','winding','电机绕组与线圈制造',r'motor|电机',r'winding|coil|绕组|线圈')
R('M264','cover','电池盖板、端子与密封结构',B,r'cover.plate|terminal|cap.assembly|盖板|顶盖|极柱|端盖|密封',r'assembling.device|assembly.equipment|manufacturing.equipment|组装装置|制造设备|生产设备')
R('M379','module','电池模组与电池包装配结构',r'battery.module|battery.pack|电池模组|电池包',r'structure|assembly|housing|frame|结构|装配|壳体|框架',r'clamp|fixture|工装|夹具')
R('M040','manufacturing','电池装配工装与制造设备',B,r'fixture|clamping|pressing.device|manufacturing.equipment|工装|夹具|压紧装置|加压装置|制造设备|组装装置')
R('M007','coating','电池电极涂布与辊压',r'\belectrodes?\b|\bbatter(?:y|ies)\b|电极|电池',r'coating|calender|涂布|辊压',r'electrodeposited|electrodeposition|电沉积')
R('M216','tab_welding','电池极耳焊接',B,r'tab.weld|极耳焊接',r'earphone|耳机')
R('M277','cable_material','电缆绝缘护套与导体结构',r'cable|电缆',r'insulation|sheath|conductor|绝缘|护套|导体')
R('M390','cable_support','电缆桥架与线束支撑',r'cable|wiring.harness|电缆|线束',r'tray|support|fasten|桥架|支撑|固定')
R('M134','connector','电连接器与接线端子',r'electrical.connector|electric.connector|terminal.block|电连接器|接线端子')
R('M381','air_cooling','电气设备风冷散热',r'electrical.equipment|power.electronic|motor|电气设备|电力电子|电机|配电柜',r'air.cooling|fan.cooling|风冷|风扇散热')
R('M381','liquid_cooling','电气设备液冷散热',r'electrical.equipment|power.electronic|motor|电气设备|电力电子|电机',r'liquid.cooling|液冷',r'battery|电池')
R('M194','temperature_control','电气设备温度监测与控制',r'electrical.equipment|power.electronic|电气设备|电力电子|配电柜',r'temperature.control|temperature.monitor|温度控制|温度监测')
R('M303','temperature_sensing','温度传感与测量装置',r'temperature.sensor|temperature.measurement|温度传感|测温装置|温度测量')
R('M262','current','电流检测与测量电路',r'current.sens|current.measurement|current.detection|电流检测|电流测量|电流传感')
R('M262','voltage','电压检测与测量电路',r'voltage.sens|voltage.measurement|voltage.detection|电压检测|电压测量|电压传感')
R('M263','surge','浪涌与过压保护电路',r'protection.circuit|protective.circuit|保护电路',r'surge|overvoltage|浪涌|过压')
R('M263','leakage','漏电与剩余电流保护',r'leakage.current|residual.current|漏电|剩余电流',r'protect|保护')
R('M434','pv_cleaning','光伏清扫机器人',r'robot|机器人',r'photovoltaic|solar.panel|光伏|太阳能板',r'inspection|巡检')
R('M434','substation_robot','变电站巡检机器人',r'robot|机器人',r'substation|变电站')

# Thermal, wind, nuclear, environmental policy and other broad parents.
R('M003','offshore_economics','海上风电开发与技术经济',r'offshore.wind|海上风电',r'econom|cost|development|经济|成本|开发')
R('M003','wind_resources','风能资源评估与选址',r'wind.resource|wind.energy|风能资源|风能',r'assessment|potential|site.selection|评估|潜力|选址')
R('M325','floating_wind','漂浮式海上风电平台',r'floating.offshore.wind|floating.wind.turbine|漂浮式海上风电|浮式风机|浮式风电')
R('M120','wave_energy','波浪能转换装置',r'wave.energy.converter|wave.energy.device|波浪能转换|波浪能装置')
R('M397','hydropower_dispatch','水电站运行调度',r'hydropower|hydroelectric|水电站|水力发电',r'dispatch|scheduling|operation|调度|运行')
R('M397','turbines','水轮机性能与设计',r'hydraulic.turbine|hydro.turbine|water.turbine|水轮机',r'performance|design|性能|设计')
R('M116','refrigerants','制冷工质及其热物性',r'refrigerant|制冷剂|制冷工质',r'propert|mixture|物性|混合|替代')
R('M116','compression','蒸汽压缩制冷循环',r'vapor.compression|vapour.compression|蒸汽压缩',r'refrigerat|heat.pump|制冷|热泵')
R('M306','absorption','吸收式制冷循环',r'absorption.refrigerat|absorption.chill|吸收式制冷|吸收式冷')
R('M306','adsorption','吸附式制冷循环',r'adsorption.refrigerat|adsorption.chill|吸附式制冷|吸附式冷')
R('M254','district','区域供热供冷系统',r'district.heat|district.cool|区域供热|区域供冷|集中供热')
R('M288','ground_heat_pump','地源热泵与地埋换热器',r'ground.source.heat.pump|ground.heat.exchanger|borehole.heat.exchanger|地源热泵|地埋换热器')
R('M288','air_heat_pump','空气源热泵',r'air.source.heat.pump|空气源热泵')
R('M252','orc','有机朗肯循环余热发电',r'organic.rankine|有机朗肯')
R('M252','brayton','超临界二氧化碳布雷顿循环',r'supercritical.CO2|supercritical.carbon.dioxide|超临界二氧化碳',r'brayton|cycle|布雷顿|循环')
R('M477','latent','潜热储热系统',r'thermal.energy.storage|heat.storage|储热',r'latent.heat|phase.change|潜热|相变')
R('M477','thermochemical','热化学储热系统',r'thermochemical.heat.storage|thermochemical.energy.storage|热化学储热')
R('M311','heat_exchanger','换热器结构与传热强化',r'heat.exchanger|换热器',r'heat.transfer|enhanc|design|传热|强化|设计',r'ground|地埋|borehole|钻孔')
R('M097','building_cooling','建筑冷却与被动降温',r'building|建筑',r'passive.cooling|radiative.cooling|被动冷却|辐射降温|被动降温')
R('M455','retrofit','建筑节能改造',r'building|建筑',r'energy.retrofit|energy.renovation|节能改造')
R('M455','hvac','建筑暖通空调能耗',r'building|建筑',r'HVAC|heating.ventilation|暖通空调|空调能耗')
R('M230','industrial_audit','工业能源审计与节能评估',r'industrial|industry|工厂|工业',r'energy.audit|energy.efficiency.assessment|energy.saving|能源审计|能效评估|节能')
R('M211','exploration','地热资源勘探与储层建模',r'geothermal|地热',r'explorat|reservoir|geophysical|geochem|勘探|储层|地球物理|地球化学')
R('M211','utilization','地热供热与发电利用',r'geothermal|地热',r'power.plant|district.heat|energy.utili|发电|供热|能源利用')
R('M103','gas_turbine','燃气轮机热力性能',r'gas.turbine|燃气轮机',r'thermal|performance|cycle|热力|性能|循环')
R('M430','diesel','柴油机燃烧与排放',r'diesel.engine|柴油机',r'combustion|emission|燃烧|排放')
R('M430','dual_fuel','双燃料发动机',r'dual.fuel.engine|双燃料发动机')
R('M385','boiler','电站锅炉运行与燃烧',r'power.plant.boiler|utility.boiler|电站锅炉',r'operation|combustion|运行|燃烧')
R('M385','steam_turbine','汽轮机运行与热力性能',r'steam.turbine|汽轮机',r'operation|performance|运行|性能')
R('M045','coal_gasification','煤气化工艺与反应',r'coal.gasification|coal.gasifier|煤气化')
R('M042','gas_hydrate','天然气水合物生成与分解',r'gas.hydrate|methane.hydrate|天然气水合物|甲烷水合物',r'formation|dissociation|生成|分解')
R('M386','gas_network','天然气管网优化运行',r'natural.gas.network|gas.pipeline|天然气管网|输气管道',r'optimization|operation|优化|运行')
R('M032','oil_price','石油价格与市场经济',r'oil.price|petroleum.price|油价|石油价格')
R('M032','oil_industry','石油产业投资与经营',r'oil.industry|petroleum.industry|石油产业|石油行业',r'investment|management|投资|经营')
R('M290','fission','核裂变反应堆工程',r'fission.reactor|nuclear.fission|light.water.reactor|核裂变|轻水堆|压水堆')
R('M290','fusion','核聚变装置工程',r'fusion.reactor|fusion.device|tokamak|聚变堆|聚变装置|托卡马克','',r'diagnos|imaging|lost.alpha|诊断|成像')
R('M182','beam','聚变加热与中性束注入',r'fusion|tokamak|聚变|托卡马克',r'neutral.beam|heating|中性束|加热')
R('M323','mhd','磁约束等离子体MHD稳定性',r'plasma|等离子体',r'magnetohydrodynamic|MHD.stability|磁流体|MHD稳定')
R('M391','irradiation','核结构材料辐照损伤',r'steel|tungsten|structural.material|钢|钨|结构材料',r'irradiation.damage|radiation.damage|辐照损伤')
R('M457','astrophysics','天体等离子体与磁重联',r'astrophysic|solar.wind|magnetosphere|天体|太阳风|磁层',r'plasma|reconnection|等离子体|磁重联')
R('M267','deicing','电力设施覆冰与除冰',r'power.line|wind.turbine|电力线路|输电线路|风机',r'icing|de.icing|覆冰|除冰')
R('M460','irrigation','灌溉水资源优化调度',r'irrigation|灌溉',r'water.resource|scheduling|optimization|水资源|调度|优化')
R('M328','forest_management','森林资源经营与碳汇',r'forest|森林',r'management|carbon.sequestration|经营|碳汇')
R('M467','wood_processing','木材加工与干燥',r'wood|timber|木材',r'processing|drying|加工|干燥')
R('M432','adaptation','气候变化适应与风险',r'climate.change|气候变化',r'adaptation|vulnerability|climate.risk|适应|脆弱性|气候风险')
R('M432','mitigation','气候变化减缓政策',r'climate.change|climate.policy|气候变化|气候政策',r'mitigation|减缓|减排',r'adaptation|适应')
R('M219','international','国际气候协定与治理',r'climate|气候',r'Paris.agreement|UNFCCC|international.negotiation|巴黎协定|国际谈判|国际治理')
R('M266','green_finance','绿色金融与能源投资',r'green.finance|green.bond|绿色金融|绿色债券')
R('M499','energy_poverty','能源贫困与能源可及性',r'energy.poverty|energy.access|能源贫困|能源可及')
R('M171','energy_security','能源安全与转型战略',r'energy.security|能源安全',r'transition|strateg|转型|战略')
R('M319','regional_carbon','中国区域低碳经济与碳效率',r'China|Chinese|中国|省域|城市群',r'carbon.efficiency|low.carbon.econom|碳效率|低碳经济')
R('M132','emissions_trading','碳排放交易机制',r'emissions.trading|carbon.trading|碳排放交易|碳交易')
R('M065','carbon_tax','碳税与环境税费',r'carbon.tax|environmental.tax|碳税|环境税')
R('M065','subsidy','可再生能源补贴机制',r'renewable.energy|solar|wind|可再生能源|光伏|风电',r'subsid|补贴')
R('M053','transmission_tariff','输配电价监管政策',r'输配电价|transmission.tariff|distribution.tariff',r'通知|监管|regulat|policy')
R('M053','retail_tariff','销售电价与用户电费政策',r'销售电价|工商业电价|居民电价|retail.electricity.tariff',r'通知|政策|policy|regulat')
R('M364','charging_policy','充电基础设施建设政策',r'充电基础设施|充电桩|充电站',r'通知|意见|办法|规划|政策')
R('M364','utility_connection','公用事业接入与收费政策',r'供水|供电|供气|公用事业',r'接入|接网|报装|收费',r'充电')
R('M336','energy_label','能效标识与产品能效政策',r'能效标识|能效标准|energy.label',r'通知|办法|标准|regulat')
R('M005','grid_construction','电网建设与供电服务政策',r'电网建设|供电服务|农网改造',r'通知|意见|办法|规划')
R('M287','standards','能源电力标准化政策',r'能源|电力',r'标准化|行业标准|国家标准')
R('M217','electrical_safety','电气安全与触电风险',r'electrical.safety|electric.shock|电气安全|触电')
R('M459','risk_warning','电力设备风险预警',r'电力|电网|power.system',r'risk.warning|risk.assessment|风险预警|风险评估')

# Correctable mixtures in materials and generic-method parent buckets.
R('M011','dielectric_storage','聚合物介电储能',r'polymer|聚合物',r'dielectric.energy.storage|energy.storage.density|介电储能|储能密度')
R('M011','electrical_insulation','聚合物电气绝缘',r'polymer|聚合物',r'electrical.insulation|dielectric.breakdown|电气绝缘|介电击穿')
R('M068','gan','氮化镓功率与结器件',r'gallium.nitride|\bGaN\b|氮化镓',r'transistor|HEMT|power.device|晶体管|功率器件')
R('M429','sic','碳化硅功率器件',r'silicon.carbide|\bSiC\b|碳化硅',r'MOSFET|power.device|Schottky.diode|功率器件|肖特基','',False)
R('M152','sic_ceramic','碳化硅陶瓷结构材料',r'silicon.carbide|\bSiC\b|碳化硅',r'ceramic|sinter|陶瓷|烧结',r'MOSFET|power.device|功率器件')
R('M198','copper_thermoelectric','铜基热电材料',r'copper|Cu2Se|Cu2S|铜基|硒化铜|硫化铜',r'thermoelectric|热电')
R('M121','thermoelectric','热电材料性能调控',r'thermoelectric.material|thermoelectric.propert|热电材料|热电性能',r'Seebeck|ZT|figure.of.merit|掺杂|doping|塞贝克','',False)
R('M251','permanent_magnet','永磁材料与磁性设计',r'permanent.magnet.material|NdFeB|Nd.Fe.B|永磁材料|钕铁硼')
R('M251','soft_magnetic','软磁材料与磁损耗',r'soft.magnetic|软磁',r'loss|propert|损耗|性能')
R('M202','triboelectric','摩擦纳米发电机',r'triboelectric.nanogenerator|摩擦纳米发电机')
R('M016','piezoelectric','压电能量采集',r'piezoelectric|压电',r'energy.harvest|能量采集')
R('M016','electromagnetic','电磁能量采集',r'electromagnetic|电磁',r'energy.harvest|能量采集')
R('M113','water_harvesting','大气集水与雾水采集',r'atmospheric.water.harvest|fog.harvest|大气集水|空气取水|雾水采集')
R('M113','oil_water','油水分离界面与膜材料',r'oil.water.separat|油水分离')
R('M193','lithium_extraction','锂资源提取与分离',r'lithium|锂',r'extraction|extracting|separation|提取|提锂|分离',r'spent.batter|废旧电池|recycl|回收')
R('M373','uranium','铀钍提取与分离',r'uranium|thorium|铀|钍',r'extraction|separation|adsorption|提取|分离|吸附')
R('M373','rare_earth','稀土元素提取分离',r'rare.earth|稀土',r'extraction|separation|提取|分离')
R('M339','cobalt_oer','钴基材料析氧催化',r'cobalt|Co3O4|钴',r'oxygen.evolution|析氧',r'oxygen.reduction|氧还原')
R('M145','iron_orr','铁基材料氧还原催化',r'iron|Fe.N.C|铁基|铁氮碳',r'oxygen.reduction|氧还原')
R('M265','single_atom_orr','单原子氧还原催化剂',r'single.atom|单原子',r'oxygen.reduction|氧还原')
R('M125','gcn_h2','氮化碳光催化制氢',r'carbon.nitride|g.C3N4|氮化碳',r'photocatalytic.hydrogen|光催化制氢|光催化析氢')
R('M127','graphene_membrane','石墨烯分离膜',r'graphene|石墨烯',r'separation.membrane|desalination|分离膜|海水淡化')
R('M127','graphene_composite','石墨烯结构复合材料',r'graphene|石墨烯',r'mechanical.propert|reinforcement|力学性能|增强',r'electrode|battery|supercapacitor|电极|电池|超级电容')
R('M462','hydraulic_pump','液压泵性能与控制',r'hydraulic.pump|液压泵',r'performance|control|性能|控制')
R('M462','hydraulic_valve','液压阀设计与控制',r'hydraulic.valve|液压阀',r'design|control|设计|控制')
R('M295','hil','电力系统硬件在环仿真',r'power.system|power.electronic|电力系统|电力电子',r'hardware.in.the.loop|硬件在环')
R('M295','education','能源电力教学实验平台',r'energy|electrical|power|能源|电气|电力',r'teaching|education|laboratory.platform|教学|实验平台')
R('M481','intrusion','网络入侵检测',r'network.intrusion|intrusion.detection|网络入侵|入侵检测')
R('M361','knowledge_graph','电力知识图谱',r'power|electric|电力|电网',r'knowledge.graph|知识图谱')

# Canonical precedence for nested *material* specializations: same reaction owner.
# These methods/materials become attributes of the reaction instead of duplicate leaves.
for rule in RULES:
    if rule['rule_id']=='M007.coating':
        rule['required_text_pattern']=B
    if rule['rule_id'] in ['M049.solid','M049.gel']:
        rule['required_text_pattern']=r'lithium|\bLiClO4\b|\bLiTFSI\b|\bLiFSI\b|锂'
    if rule['rule_id']=='M482.pemfc':
        rule.update(topic_id='M419',parent_id='M419',is_child=False,name='质子交换膜燃料电池运行与建模')
    if rule['rule_id']=='M125.gcn_h2':
        rule.update(topic_id='M010.photocatalytic_h2',parent_id='M010',is_child=False,
                    name='光催化制氢',attribute='氮化碳催化剂')
    if rule['rule_id'] in ['M339.cobalt_oer','M145.iron_orr','M265.single_atom_orr']:
        parent='M154' if rule['rule_id']=='M339.cobalt_oer' else 'M363'
        rule.update(topic_id=parent,parent_id=parent,is_child=False,
                    name='电催化析氧' if parent=='M154' else '氧还原电催化',attribute=rule['name'])

R('M393','oled','有机发光二极管与发光材料',r'organic.light.emitting.diode|organic.light.emitting.device|\bOLEDs?\b|有机发光二极管','','',False)
R('M059','supercapacitor','超级电容器电极与器件',r'supercapacitor|超级电容器','','',False)
R('M360','dssc','染料敏化太阳能电池材料与器件',r'dye.sensiti[sz]ed.solar|\bDSSCs?\b|染料敏化太阳能','','',False)
R('M153','wireless_power','无线电能传输电路与系统',r'wireless.power.transfer|wireless.energy.transfer|无线电能传输|无线能量传输','','',False)
R('M041','wireless_charger','无线充电器与装置',r'wireless.charg|无线充电',r'charger|device|charging.system|充电器|装置|充电系统')
R('M494','microbial_fc','微生物燃料电池与生物产电',r'microbial.fuel.cell|微生物燃料电池','','',False)
R('M335','solar_evaporation','太阳能界面蒸发与海水淡化',r'solar|太阳能',r'interfacial.evaporation|steam.generation|界面蒸发|蒸汽发生','',False)
R('M389','rail','轨道交通能耗与牵引优化',r'railway|rail.transit|铁路|轨道交通',r'energy.consumption|traction|能耗|牵引')
R('M389','shipping','船舶燃料与能效',r'ship|maritime|船舶|航运',r'fuel|energy.efficiency|燃料|能效')
R('M023','tidal','潮汐与潮流能开发',r'tidal.energy|tidal.stream|潮汐能|潮流能')
R('M307','led_lighting','LED照明灯具与配光',r'LED|light.emitting.diode|发光二极管',r'lighting|luminaire|light.distribution|照明|灯具|配光',r'organic|有机')

assert len({r['rule_id'] for r in RULES})==len(RULES)
assert all(isinstance(r['is_child'],bool) for r in RULES)
